//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HtcSharp.HttpModule {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    // SourceTools-Start
    // Ignore-Copyright
    // SourceTools-End
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HtcSharp.HttpModule.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument cannot be null or empty..
        /// </summary>
        internal static string ArgumentCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("ArgumentCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; method must not have ref or out parameters..
        /// </summary>
        internal static string Exception_InvokeDoesNotSupportRefOrOutParams {
            get {
                return ResourceManager.GetString("Exception_InvokeDoesNotSupportRefOrOutParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to resolve service for type &apos;{0}&apos; while attempting to Invoke middleware &apos;{1}&apos;..
        /// </summary>
        internal static string Exception_InvokeMiddlewareNoService {
            get {
                return ResourceManager.GetString("Exception_InvokeMiddlewareNoService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path in &apos;{0}&apos; must start with &apos;/&apos;..
        /// </summary>
        internal static string Exception_PathMustStartWithSlash {
            get {
                return ResourceManager.GetString("Exception_PathMustStartWithSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be greater than zero..
        /// </summary>
        internal static string Exception_PortMustBeGreaterThanZero {
            get {
                return ResourceManager.GetString("Exception_PortMustBeGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple public &apos;{0}&apos; or &apos;{1}&apos; methods are available..
        /// </summary>
        internal static string Exception_UseMiddleMutlipleInvokes {
            get {
                return ResourceManager.GetString("Exception_UseMiddleMutlipleInvokes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types that implement &apos;{0}&apos; do not support explicit arguments..
        /// </summary>
        internal static string Exception_UseMiddlewareExplicitArgumentsNotSupported {
            get {
                return ResourceManager.GetString("Exception_UseMiddlewareExplicitArgumentsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not available..
        /// </summary>
        internal static string Exception_UseMiddlewareIServiceProviderNotAvailable {
            get {
                return ResourceManager.GetString("Exception_UseMiddlewareIServiceProviderNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No public &apos;{0}&apos; or &apos;{1}&apos; method found for middleware of type &apos;{2}&apos;..
        /// </summary>
        internal static string Exception_UseMiddlewareNoInvokeMethod {
            get {
                return ResourceManager.GetString("Exception_UseMiddlewareNoInvokeMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No service for type &apos;{0}&apos; has been registered..
        /// </summary>
        internal static string Exception_UseMiddlewareNoMiddlewareFactory {
            get {
                return ResourceManager.GetString("Exception_UseMiddlewareNoMiddlewareFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; or &apos;{1}&apos; does not return an object of type &apos;{2}&apos;..
        /// </summary>
        internal static string Exception_UseMiddlewareNonTaskReturnType {
            get {
                return ResourceManager.GetString("Exception_UseMiddlewareNonTaskReturnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;{0}&apos; or &apos;{1}&apos; method&apos;s first argument must be of type &apos;{2}&apos;..
        /// </summary>
        internal static string Exception_UseMiddlewareNoParameters {
            get {
                return ResourceManager.GetString("Exception_UseMiddlewareNoParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; failed to create middleware of type &apos;{1}&apos;..
        /// </summary>
        internal static string Exception_UseMiddlewareUnableToCreateMiddleware {
            get {
                return ResourceManager.GetString("Exception_UseMiddlewareUnableToCreateMiddleware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An element with the key &apos;{0}&apos; already exists in the {1}..
        /// </summary>
        internal static string RouteValueDictionary_DuplicateKey {
            get {
                return ResourceManager.GetString("RouteValueDictionary_DuplicateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; defines properties &apos;{1}&apos; and &apos;{2}&apos; which differ only by casing. This is not supported by {3} which uses case-insensitive comparisons..
        /// </summary>
        internal static string RouteValueDictionary_DuplicatePropertyName {
            get {
                return ResourceManager.GetString("RouteValueDictionary_DuplicatePropertyName", resourceCulture);
            }
        }

        internal static string FormatException_InvokeDoesNotSupportRefOrOutParams(object address) {
            return Resources.Exception_InvokeDoesNotSupportRefOrOutParams
                .Replace("{0}", address.ToString());
        }

        internal static string FormatException_InvokeMiddlewareNoService(object p0, object p1) {
            return Resources.Exception_InvokeMiddlewareNoService
                .Replace("{0}", p0.ToString())
                .Replace("{1}", p1.ToString());
        }

        internal static string FormatException_PathMustStartWithSlash(object p0) {
            return Resources.Exception_PathMustStartWithSlash
                .Replace("{0}", p0.ToString());
        }

        internal static string FormatException_UseMiddleMutlipleInvokes(object p0, object p1) {
            return Resources.Exception_UseMiddleMutlipleInvokes
                .Replace("{0}", p0.ToString())
                .Replace("{1}", p1.ToString());
        }

        internal static string FormatException_UseMiddlewareExplicitArgumentsNotSupported(object p0) {
            return Resources.Exception_UseMiddlewareExplicitArgumentsNotSupported
                .Replace("{0}", p0.ToString());
        }

        internal static string FormatException_UseMiddlewareIServiceProviderNotAvailable(object p0) {
            return Resources.Exception_UseMiddlewareIServiceProviderNotAvailable
                .Replace("{0}", p0.ToString());
        }

        internal static string FormatException_UseMiddlewareNoInvokeMethod(object p0, object p1, object p2) {
            return Resources.Exception_UseMiddlewareNoInvokeMethod
                .Replace("{0}", p0.ToString())
                .Replace("{1}", p1.ToString())
                .Replace("{2}", p2.ToString());
        }

        internal static string FormatException_UseMiddlewareNoMiddlewareFactory(object p0) {
            return Resources.Exception_UseMiddlewareNoMiddlewareFactory
                .Replace("{0}", p0.ToString());
        }

        internal static string FormatException_UseMiddlewareNonTaskReturnType(object p0, object p1, object p2) {
            return Resources.Exception_UseMiddlewareNonTaskReturnType
                .Replace("{0}", p0.ToString())
                .Replace("{1}", p1.ToString());
        }

        internal static string FormatException_UseMiddlewareNoParameters(object p0, object p1, object p2) {
            return Resources.Exception_UseMiddlewareNoParameters
                .Replace("{0}", p0.ToString())
                .Replace("{1}", p1.ToString());
        }

        internal static string FormatException_UseMiddlewareUnableToCreateMiddleware(object p0, object p1) {
            return Resources.Exception_UseMiddlewareUnableToCreateMiddleware
                .Replace("{0}", p0.ToString())
                .Replace("{1}", p1.ToString());
        }

        internal static string FormatRouteValueDictionary_DuplicateKey(object p0, object p1) {
            return Resources.Exception_InvokeDoesNotSupportRefOrOutParams
                .Replace("{0}", p0.ToString())
                .Replace("{1}", p1.ToString());
        }

        internal static string FormatRouteValueDictionary_DuplicatePropertyName(object p0, object p1, object p2, object p3) {
            return Resources.RouteValueDictionary_DuplicatePropertyName
                .Replace("{0}", p0.ToString())
                .Replace("{1}", p1.ToString())
                .Replace("{2}", p2.ToString())
                .Replace("{3}", p3.ToString());
        }
    }
}
